"""auto update

Revision ID: 16b35b18b6b6
Revises: cef1ecea14c1
Create Date: 2026-03-09 16:32:38.730388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16b35b18b6b6'
down_revision: Union[str, Sequence[str], None] = 'cef1ecea14c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('manager_rep_id', sa.Integer(), nullable=False),
    sa.Column('assigned_rep_id', sa.Integer(), nullable=False),
    sa.Column('assignment_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_assignments_id'), 'user_assignments', ['id'], unique=False)
    op.drop_column('agreements', 'bonus_qty_threshold')
    op.drop_column('agreements', 'bonus_qty')
    op.drop_column('doctors', 'doctor_class')
    op.drop_column('order_items', 'gift_qty')
    op.drop_column('order_items', 'has_deal')
    op.drop_column('orders', 'printed_by')
    op.drop_column('orders', 'accounting_approved_by')
    op.drop_column('orders', 'manager_approved_by')
    op.drop_column('orders', 'delivered_at')
    op.drop_column('orders', 'delivered_by')
    op.drop_column('orders', 'accounting_approved_at')
    op.drop_column('orders', 'manager_approved_at')
    op.drop_column('orders', 'printed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('printed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('manager_approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('accounting_approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('delivered_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('manager_approved_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('accounting_approved_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('printed_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('order_items', sa.Column('has_deal', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('order_items', sa.Column('gift_qty', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('doctors', sa.Column('doctor_class', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('agreements', sa.Column('bonus_qty', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('agreements', sa.Column('bonus_qty_threshold', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_assignments_id'), table_name='user_assignments')
    op.drop_table('user_assignments')
    # ### end Alembic commands ###