"""auto update

Revision ID: 6aa9365711e5
Revises: 71102f8d9b4e
Create Date: 2026-03-19 15:25:59.858927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aa9365711e5'
down_revision: Union[str, Sequence[str], None] = '71102f8d9b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('return_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('agreement_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_items_id'), 'return_items', ['id'], unique=False)
    op.add_column('returns', sa.Column('invoice_number', sa.String(), nullable=True))
    op.alter_column('returns', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('returns', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('returns', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('returns', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('returns', 'invoice_number')
    op.drop_index(op.f('ix_return_items_id'), table_name='return_items')
    op.drop_table('return_items')
    # ### end Alembic commands ###