"""auto update

Revision ID: 82aa70b47289
Revises: 10cd840b9aa4
Create Date: 2026-03-14 16:42:54.823608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82aa70b47289'
down_revision: Union[str, Sequence[str], None] = '10cd840b9aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('rep_name', sa.String(), nullable=True),
    sa.Column('report_date', sa.String(), nullable=True),
    sa.Column('total_visits', sa.Integer(), nullable=True),
    sa.Column('completed_count', sa.Integer(), nullable=True),
    sa.Column('cancelled_count', sa.Integer(), nullable=True),
    sa.Column('deal_count', sa.Integer(), nullable=True),
    sa.Column('quota_count', sa.Integer(), nullable=True),
    sa.Column('followup_count', sa.Integer(), nullable=True),
    sa.Column('report_data', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_reports_id'), 'daily_reports', ['id'], unique=False)
    op.add_column('visits', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'tags')
    op.drop_index(op.f('ix_daily_reports_id'), table_name='daily_reports')
    op.drop_table('daily_reports')
    # ### end Alembic commands ###