"""auto update

Revision ID: b197a7a13755
Revises: d003a9105fb7
Create Date: 2026-03-14 05:10:19.804387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b197a7a13755'
down_revision: Union[str, Sequence[str], None] = 'd003a9105fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('can_import', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('permissions', sa.Column('can_export', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'can_export')
    op.drop_column('permissions', 'can_import')
    # ### end Alembic commands ###