"""auto update

Revision ID: d003a9105fb7
Revises: 906bac286843
Create Date: 2026-03-13 05:39:58.091506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd003a9105fb7'
down_revision: Union[str, Sequence[str], None] = '906bac286843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_area_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('page', sa.String(), nullable=False),
    sa.Column('can_view', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('can_add', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('can_edit', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('can_delete', sa.Boolean(), server_default='false', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('representative_areas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('representative_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_representative_areas_id'), 'representative_areas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_representative_areas_id'), table_name='representative_areas')
    op.drop_table('representative_areas')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###